spring:
  application:
    name: java-service
  jpa:
    show-sql: true
    database-platform: '@spring.jpa.database-platform@'
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
  properties:
    hibernate:
      format_sql: true

  datasource:
    url: '@spring.datasource.url@'
    username: '@spring.datasource.username@'
    password: '@spring.datasource.password@'
    driver-class-name: '@spring.datasource.driver-class-name@'
    hikari:
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000
      poolName: HikariPoolBooks
  h2:
    console:
      enabled: true
      path: /h2-console
  logging:
    level.org.hibernate.SQL: DEBUG
    level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE
swagger:
  host: '@swagger.host@'